[package]
name = "nebula-parameter-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
thiserror = { workspace = true }
chrono = { workspace = true }

nebula-parameter = { path = "../nebula-parameter" }
nebula-value = { path = "../nebula-value" }
nebula-core = { path = "../nebula-core" }

egui = "0.33.3"
egui_extras = { version = "0.33.3", features = ["chrono"] }
egui_flex = "0.5.0"
egui_dock = "0.18.0"
egui_file = "0.24"
egui-phosphor = { version = "0.11.0", features = ["regular"] }
eframe = { version = "0.33.3", features = ["glow"] }
